#!/usr/bin/env python3
"""Regenerate the Arabic side of Hidden/Resources/Localizable.xcstrings.

The English keys are the source strings as written in code; Xcode treats a key with no
localization entry as falling back to the key itself, so English needs no entries here.

    python Scripts/make_string_catalog.py
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Hidden", "Resources", "Localizable.xcstrings")

AR = {
    "1 Hour": "ساعة واحدة",
    "10 Minutes": "10 دقائق",
    "10 Seconds": "10 ثوانٍ",
    "15 Minutes": "15 دقيقة",
    "2 Minutes": "دقيقتان",
    "2 Seconds": "ثانيتان",
    "25 Items": "25 عنصرًا",
    "3 Seconds": "3 ثوانٍ",
    "30 Minutes": "30 دقيقة",
    "30 Seconds": "30 ثانية",
    "5 Minutes": "5 دقائق",
    "5 Seconds": "5 ثوانٍ",
    "50 Items": "50 عنصرًا",
    "A sample across time": "عيّنة عبر الزمن",
    "About": "حول",
    "About the Hidden Album": "حول ألبوم المخفي",
    "After 1 Minute": "بعد دقيقة",
    "After 30 Seconds": "بعد 30 ثانية",
    "After 5 Minutes": "بعد 5 دقائق",
    "All Hidden": "كل المخفي",
    "All reviewed": "تمت مراجعة الكل",
    "Allow Photos Access": "السماح بالوصول إلى الصور",
    "Any": "الكل",
    "App Favorite": "مفضلة التطبيق",
    "App Favorites": "مفضلات التطبيق",
    "Appearance": "المظهر",
    "Apple protects the system Hidden album independently of any app.":
        "تحمي Apple ألبوم المخفي في النظام بشكل مستقل عن أي تطبيق.",
    "Autoplay Next": "تشغيل التالي تلقائيًا",
    "Bar chart of items captured per year": "رسم بياني للعناصر الملتقطة في كل سنة",
    "Blur Thumbnails": "تمويه المصغّرات",
    "Buried": "مدفون",
    "Captured": "تاريخ الالتقاط",
    "Captured by Year": "الالتقاط حسب السنة",
    "Captured on this date in past years": "التُقطت في هذا اليوم في سنوات ماضية",
    "Check Again": "تحقق مرة أخرى",
    "Clear All Filters": "مسح كل الفلاتر",
    "Clear Filters": "مسح الفلاتر",
    "Clear History": "مسح السجل",
    "Clear Image Cache": "مسح ذاكرة الصور المؤقتة",
    "Clear Viewing History": "مسح سجل المشاهدة",
    "Clear all viewing history? Tags, notes and favorites stay.":
        "هل تريد مسح كل سجل المشاهدة؟ ستبقى الوسوم والملاحظات والمفضلات.",
    "Close": "إغلاق",
    "Dark": "داكن",
    "Data": "البيانات",
    "Dates": "التواريخ",
    "Deep Archive": "الأرشيف العميق",
    "Default Sort": "الترتيب الافتراضي",
    "Dimensions": "الأبعاد",
    "Discover": "استكشاف",
    "Done": "تم",
    "Duration": "المدة",
    "Every item played once — nothing repeated.": "عُرض كل عنصر مرة واحدة — دون أي تكرار.",
    "Everything Hidden stores is a small local metadata layer. Your media lives in Apple Photos and is never duplicated or uploaded.":
        "كل ما يخزّنه «المخفي» هو طبقة بيانات وصفية محلية صغيرة. وسائطك تبقى في تطبيق الصور ولا تُنسخ ولا تُرفع أبدًا.",
    "Favorite": "مفضلة",
    "Favorited": "أُضيفت للمفضلة",
    "Favorites": "المفضلة",
    "Favorites you haven't seen lately": "مفضلات لم ترها مؤخرًا",
    "Filters": "الفلاتر",
    "First 25": "أول 25",
    "First Observed Favorite": "أول رصد كمفضلة",
    "First Observed by Hidden": "أول رصد في التطبيق",
    "First look at your Hidden library": "أول نظرة على مكتبتك المخفية",
    "Forgotten": "منسي",
    "Forgotten Videos": "فيديوهات منسية",
    "Has Location": "يحتوي على موقع",
    "Hidden": "المخفي",
    "Hidden needs access to your Photos library to show your hidden media. You can allow it in Settings.":
        "يحتاج التطبيق إلى الوصول لمكتبة الصور لعرض وسائطك المخفية. يمكنك السماح بذلك من الإعدادات.",
    "Hidden never duplicates your originals; it only keeps its own small notes.":
        "لا ينسخ التطبيق ملفاتك الأصلية أبدًا؛ يحتفظ فقط بملاحظاته الصغيرة.",
    "Hidden's own Face ID lock protects this app. It is independent of Apple's protection and cannot unlock Apple's Hidden album.":
        "قفل بصمة الوجه في هذا التطبيق يحمي التطبيق نفسه فقط، وهو مستقل عن حماية Apple ولا يمكنه فتح ألبوم المخفي الخاص بالنظام.",
    "If your Hidden album appears empty here, either nothing is hidden, or the system protection is on. Turning that protection off in Photos settings makes hidden media visible to this app.":
        "إذا ظهر ألبوم المخفي فارغًا هنا، فإما أنه لا توجد عناصر مخفية، أو أن حماية النظام مفعّلة. إيقاف تلك الحماية من إعدادات الصور يجعل الوسائط المخفية مرئية لهذا التطبيق.",
    "Immediately": "فورًا",
    "In Pool": "في المجموعة",
    "In This App": "في هذا التطبيق",
    "Inbox": "الوارد",
    "Incognito": "التخفي",
    "Incognito stops the app recording any viewing history. Read Only stops it changing anything in Apple Photos.":
        "وضع التخفي يمنع تسجيل أي سجل مشاهدة. وضع القراءة فقط يمنع التطبيق من تغيير أي شيء في تطبيق الصور.",
    "Info": "معلومات",
    "Insights": "إحصاءات",
    "Keep Hidden": "إبقاؤه مخفيًا",
    "Kind": "النوع",
    "Landscape": "أفقي",
    "Last Viewed": "آخر مشاهدة",
    "Latest Modified": "الأحدث تعديلًا",
    "Length": "الطول",
    "Library": "المكتبة",
    "Light": "فاتح",
    "Live": "حي",
    "Live Photo": "صورة حية",
    "Live Photos": "الصور الحية",
    "Location": "الموقع",
    "Lock Now": "قفل الآن",
    "Lock the app with Face ID, separately from anything Apple protects.":
        "اقفل التطبيق ببصمة الوجه، بشكل مستقل عن أي حماية من Apple.",
    "Lock with Face ID": "القفل ببصمة الوجه",
    "Longer Than": "أطول من",
    "Longest First": "الأطول أولًا",
    "Mark Reviewed": "وضع علامة تمت المراجعة",
    "Media": "الوسائط",
    "Media Types": "أنواع الوسائط",
    "Modified": "تاريخ التعديل",
    "Most Viewed": "الأكثر مشاهدة",
    "Mute Videos by Default": "كتم الفيديو افتراضيًا",
    "Never Finished": "لم يكتمل",
    "Never Viewed": "لم يُشاهد",
    "Never opened in this app": "لم يُفتح في هذا التطبيق",
    "New": "جديد",
    "Newest Captured": "الأحدث التقاطًا",
    "Newly Favorited": "أُضيفت حديثًا للمفضلة",
    "Newly Observed": "رُصدت حديثًا",
    "Next": "التالي",
    "No Delete Mode": "وضع بلا حذف",
    "No Hidden Media Available": "لا توجد وسائط مخفية متاحة",
    "No Limit": "بلا حد",
    "No Longer Here": "لم تعد هنا",
    "No Photos Access": "لا يوجد وصول للصور",
    "No Two Videos in a Row": "لا فيديوهان متتاليان",
    "Not downloaded from iCloud": "لم تُنزّل من iCloud",
    "Not viewed in over 90 days": "لم تُشاهد منذ أكثر من 90 يومًا",
    "Nothing is uploaded, tracked or analyzed anywhere else.":
        "لا يُرفع أي شيء ولا يُتتبع ولا يُحلل في أي مكان آخر.",
    "Nothing new since the last check.": "لا جديد منذ آخر فحص.",
    "Old Favorites": "مفضلات قديمة",
    "Old, never viewed, not a favorite": "قديم، لم يُشاهد، وليس مفضلًا",
    "Oldest": "الأقدم",
    "Oldest Captured": "الأقدم التقاطًا",
    "Oldest Modified": "الأقدم تعديلًا",
    "On This Day": "في مثل هذا اليوم",
    "On this device": "على هذا الجهاز",
    "One From Every Month": "واحدة من كل شهر",
    "Open Settings": "فتح الإعدادات",
    "Order": "الترتيب",
    "Panoramas": "البانوراما",
    "Pause": "إيقاف مؤقت",
    "Photo": "صورة",
    "Photo Duration": "مدة عرض الصورة",
    "Photos": "الصور",
    "Photos First": "الصور أولًا",
    "Photos Only": "الصور فقط",
    "Photos stays the source of truth": "تطبيق الصور يبقى المصدر الأساسي",
    "Pin": "تثبيت",
    "Pinned": "المثبتة",
    "Pinned in this app": "مثبتة في هذا التطبيق",
    "Play": "تشغيل",
    "Play From": "التشغيل من",
    "Playback": "التشغيل",
    "Portrait": "عمودي",
    "Previous": "السابق",
    "Privacy": "الخصوصية",
    "Queue finished": "انتهت القائمة",
    "Random": "عشوائي",
    "Rated": "مقيّمة",
    "Read Only Mode": "وضع القراءة فقط",
    "Recently Favorited": "المفضلة حديثًا",
    "Recently Observed": "المرصودة حديثًا",
    "Rediscovery": "إعادة الاكتشاف",
    "Remove Favorite": "إزالة من المفضلة",
    "Require Again": "طلب القفل مجددًا",
    "Reset App Data": "إعادة تعيين بيانات التطبيق",
    "Reset Everything": "إعادة تعيين كل شيء",
    "Reset everything Hidden knows — tags, history, collections, queues? Your photos and videos in Apple Photos are not touched.":
        "هل تريد إعادة تعيين كل ما يعرفه التطبيق — الوسوم والسجل والمجموعات وقوائم التشغيل؟ صورك وفيديوهاتك في تطبيق الصور لن تُمس.",
    "Reshuffle": "خلط جديد",
    "Resume Last Session": "استئناف آخر جلسة",
    "Review": "المراجعة",
    "Review All": "مراجعة الكل",
    "Review Later": "مراجعة لاحقًا",
    "Reviewed": "تمت المراجعة",
    "Screenshot": "لقطة شاشة",
    "Screenshots": "لقطات الشاشة",
    "Seen Once": "شوهدت مرة",
    "Select": "تحديد",
    "Session": "الجلسة",
    "Settings": "الإعدادات",
    "Shape": "الشكل",
    "Shortest First": "الأقصر أولًا",
    "Shuffle": "خلط",
    "Slow Motion": "الحركة البطيئة",
    "Sort": "الترتيب",
    "Source": "المصدر",
    "Square": "مربع",
    "Start Shuffle": "بدء الخلط",
    "State": "الحالة",
    "System": "النظام",
    "Tagged": "موسومة",
    "The oldest hidden media": "أقدم الوسائط المخفية",
    "Time Lapse": "الفاصل الزمني",
    "Total Hidden": "إجمالي المخفي",
    "True Random": "عشوائي بحت",
    "Type": "النوع",
    "Undo": "تراجع",
    "Unlock": "فتح القفل",
    "Unlock Hidden": "فتح قفل التطبيق",
    "Unreviewed": "لم تُراجع",
    "Unseen": "غير مشاهدة",
    "Version": "الإصدار",
    "Video": "فيديو",
    "Video Duration": "مدة الفيديو",
    "Video Time": "زمن الفيديو",
    "Videos": "الفيديوهات",
    "Videos First": "الفيديوهات أولًا",
    "Videos Only": "الفيديوهات فقط",
    "Videos not played in a while": "فيديوهات لم تُشغّل منذ فترة",
    "Viewed": "شوهدت",
    "Viewed exactly once": "شوهدت مرة واحدة بالضبط",
    "Views": "المشاهدات",
    "Weighting": "الترجيح",
    "What Hidden stores": "ما الذي يخزّنه التطبيق",
    "With Location": "مع موقع",
    "Without Location": "بدون موقع",
    "Yes": "نعم",
    "You're caught up.": "أنت على اطلاع بكل شيء.",
    "Your highest view counts": "أعلى أعداد المشاهدة لديك",
    "Your own lock": "قفلك الخاص",
    "Your private favorites": "مفضلاتك الخاصة",
    "Browse, rediscover and organize the media in your Hidden album — with your library staying exactly where it is, in Apple Photos.":
        "تصفح واكتشف ونظّم الوسائط في ألبوم المخفي — بينما تبقى مكتبتك في مكانها تمامًا، داخل تطبيق الصور.",
    "Asset identifiers, tags, notes, ratings, viewing history, playback positions, collection rules and observation dates — a small local database. Never your photos or videos, and never anything sent off this device.":
        "معرّفات العناصر والوسوم والملاحظات والتقييمات وسجل المشاهدة ومواضع التشغيل وقواعد المجموعات وتواريخ الرصد — قاعدة بيانات محلية صغيرة. ليست صورك أو فيديوهاتك أبدًا، ولا يغادر أي شيء هذا الجهاز.",

    # Wave 2/3 surfaces
    "A backup carries tags, ratings, notes, collections and observation dates — never photos or videos. Identifiers that no longer resolve import as dormant records.":
        "النسخة الاحتياطية تحمل الوسوم والتقييمات والملاحظات والمجموعات وتواريخ الرصد — وليس الصور أو الفيديوهات أبدًا. المعرّفات التي لم تعد موجودة تُستورد كسجلات خاملة.",
    "Add": "إضافة",
    "Back 10 Seconds": "رجوع 10 ثوانٍ",
    "Backup": "النسخ الاحتياطي",
    "Bookmark This Moment": "إضافة علامة عند هذه اللحظة",
    "Bookmarks": "العلامات المرجعية",
    "Cancel": "إلغاء",
    "Capture Activity": "نشاط الالتقاط",
    "Captured in this period": "التُقط في هذه الفترة",
    "Continue Watching": "متابعة المشاهدة",
    "Delete": "حذف",
    "Delete this item from your Photos library? This affects Apple Photos and iCloud Photos, and moves it to Recently Deleted.":
        "هل تريد حذف هذا العنصر من مكتبة الصور؟ هذا يؤثر على تطبيق الصور وصور iCloud وينقله إلى «المحذوفة مؤخرًا».",
    "End Presentation": "إنهاء العرض",
    "Everything": "كل شيء",
    "First Observed": "أول رصد",
    "First Observed Activity": "نشاط أول رصد",
    "Forward 10 Seconds": "تقديم 10 ثوانٍ",
    "Heatmap Mode": "وضع الخريطة الحرارية",
    "Import Backup": "استيراد نسخة احتياطية",
    "Include Viewing History": "تضمين سجل المشاهدة",
    "Inferred from when this app first observed each item — not Apple's own history.":
        "مستنتجة من وقت أول رصد للتطبيق لكل عنصر — وليست سجل Apple نفسه.",
    "Less": "أقل",
    "Make this item visible again in your Photos library?":
        "هل تريد جعل هذا العنصر مرئيًا مجددًا في مكتبة الصور؟",
    "More": "المزيد",
    "More Playback Options": "خيارات تشغيل إضافية",
    "Mute": "كتم",
    "My Collections": "مجموعاتي",
    "Name": "الاسم",
    "New Smart Collection": "مجموعة ذكية جديدة",
    "New Tag": "وسم جديد",
    "Newly observed hidden": "رُصد إخفاؤه حديثًا",
    "No media available.": "لا توجد وسائط متاحة.",
    "Note": "ملاحظة",
    "Nothing to Show": "لا يوجد ما يُعرض",
    "OK": "حسنًا",
    "Observation dates appear after the app has seen your library at least once.":
        "تظهر تواريخ الرصد بعد أن يرى التطبيق مكتبتك مرة واحدة على الأقل.",
    "Playback position": "موضع التشغيل",
    "Prepare Metadata Backup": "تجهيز نسخة احتياطية للبيانات",
    "Present This Item": "عرض هذا العنصر",
    "Queue": "قائمة تشغيل",
    "Queue name": "اسم القائمة",
    "Rate": "تقييم",
    "Rating": "التقييم",
    "Recap": "ملخص",
    "Recently Finished": "المكتملة حديثًا",
    "Recently Viewed": "المشاهدة حديثًا",
    "Rediscover": "إعادة اكتشاف",
    "Restart": "إعادة التشغيل",
    "Rules": "القواعد",
    "Save": "حفظ",
    "Save as Queue": "حفظ كقائمة تشغيل",
    "Saved Queues": "قوائم التشغيل المحفوظة",
    "Sessions": "الجلسات",
    "Share Backup File": "مشاركة ملف النسخة الاحتياطية",
    "Smart collection": "مجموعة ذكية",
    "Speed": "السرعة",
    "Stores references to the selected items — never copies.":
        "تُخزَّن مراجع للعناصر المحددة — وليست نسخًا أبدًا.",
    "Tag name": "اسم الوسم",
    "Tags": "الوسوم",
    "That didn't work": "لم ينجح ذلك",
    "This file isn't a Hidden metadata backup.": "هذا الملف ليس نسخة احتياطية لبيانات التطبيق.",
    "This video isn't available right now": "هذا الفيديو غير متاح حاليًا",
    "Timeline": "الخط الزمني",
    "Timeline Date": "تاريخ الخط الزمني",
    "Unhide": "إظهار",
    "Unmute": "إلغاء الكتم",
    "Videos played to the end recently": "فيديوهات اكتملت مشاهدتها حديثًا",
    "Videos you started but didn't finish": "فيديوهات بدأتها ولم تكملها",
    "What you opened lately": "ما فتحته مؤخرًا",
    "When the media was captured": "وقت التقاط الوسائط",
    "When this app first observed it hidden": "وقت أول رصد للتطبيق لإخفائها",
    "Year, month, tag, video…": "سنة، شهر، وسم، فيديو…",
    "Open On": "الفتح على",
    "Stacks": "المجموعات المتتابعة",
    "Bursts captured together": "دفعات التُقطت معًا",
    "Possible Duplicates": "تكرارات محتملة",
    "Same second, same dimensions": "نفس الثانية ونفس الأبعاد",
    "Structure": "البنية",
    "No Stacks": "لا توجد مجموعات متتابعة",
    "Stacks appear when several photos were captured within seconds of each other.":
        "تظهر المجموعات المتتابعة عندما تُلتقط عدة صور خلال ثوانٍ من بعضها.",
    "Stack": "مجموعة متتابعة",
    "Compare": "مقارنة",
    "No Possible Duplicates": "لا توجد تكرارات محتملة",
    "Items captured in the same second with the same dimensions would appear here.":
        "العناصر الملتقطة في نفس الثانية وبنفس الأبعاد ستظهر هنا.",
    "Related": "ذات صلة",
    "Places": "الأماكن",
    "Share": "مشاركة",
    "%@ items waiting for a decision.": "%@ عنصرًا بانتظار قرار.",
    "%@ items": "%@ عنصرًا",
    "%@ videos": "%@ فيديو",
    "%@ active": "%@ مفعّلة",
    "%@ photos in a burst": "%@ صورة في دفعة واحدة",
    "Areas from existing location data": "مناطق من بيانات الموقع الموجودة",
    "No Location Data": "لا توجد بيانات موقع",
    "Media with location information would be grouped into areas here.":
        "الوسائط التي تحمل معلومات موقع ستُجمع هنا في مناطق.",
    "See All Related": "عرض كل ذات الصلة",
    "Captured around the same time, the same day, the same session, or sharing a tag.":
        "التُقطت في وقت متقارب، أو في نفس اليوم، أو في نفس الجلسة، أو تتشارك وسمًا.",
    "Cover While Screen Recording": "تغطية أثناء تسجيل الشاشة",
    "Find Text in Photos": "البحث عن نص داخل الصور",
    "Indexed": "المفهرَس",
    "Pause Indexing": "إيقاف الفهرسة مؤقتًا",
    "Resume Indexing": "استئناف الفهرسة",
    "Clear Text Index": "مسح فهرس النصوص",
    "Paused — battery is low.": "توقفت مؤقتًا — البطارية منخفضة.",
    "Recognizes text inside photos on this device so search can find it. Nothing is uploaded; iCloud originals are never downloaded for indexing.":
        "يتعرف على النص داخل الصور على هذا الجهاز ليتمكن البحث من إيجاده. لا يُرفع أي شيء، ولا تُنزَّل النسخ الأصلية من iCloud للفهرسة أبدًا.",
    "video": "فيديو",
    "photo": "صورة",
}


def main():
    data = {"sourceLanguage": "en", "strings": {}, "version": "1.0"}
    for key, value in AR.items():
        data["strings"][key] = {
            "localizations": {
                "ar": {"stringUnit": {"state": "translated", "value": value}}
            }
        }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
    print(f"wrote {OUT} with {len(AR)} keys")


if __name__ == "__main__":
    main()
